# Exported from Render on 2024-11-27T13:47:32Z
services:
- type: web
  name: esgi.4a.render.static
  runtime: static
  repo: https://github.com/kyllianmgn/esgi.4a.render.static
  buildCommand: npm install; npm run build
  staticPublishPath: dist
  routes:
  - type: redirect
    source: /*
    destination: /index.html
  envVars:
    - key: DATABASE_URL
      fromDatabase:
        name: 4a.render.static.db
        property: connectionString
version: "1"

databases:
  # A basic-4gb database instance with a read replica
  - name: 4a.render.static.db # Required
    region: frankfurt # Default: oregon
    plan: basic-4gb # Default: basic-256mb
    databaseName: prod_app # Default: generated value based on name