# Exported from Render on 2024-11-27T13:47:32Z
services:
- type: web
  name: esgi.4a.render.static
  runtime: static
  repo: https://github.com/kyllianmgn/esgi.4a.render.static
  buildCommand: npm install; npm run build
  staticPublishPath: dist
  routes:
  - type: redirect
    source: /*
    destination: /index.html
version: "1"
